### ISSUE TITLE
大佬这个功能没有实现

### ISSUE THREAD

**Issue by ww2766** [haitang1894/pea#2]
![Uploading 屏幕截图 2024-05-29 135321.png…]()

**Comment by ww2766** [comment]
![屏幕截图 2024-05-29 135321](https://github.com/haitang1894/pea/assets/145252184/6dee6542-6cfb-4854-92d5-3b730d8b38e9)

**Comment by haitang1894** [comment]
这个是前端那边 上周的新发布的东西，目前还没时间开发

**Comment by haitang1894** [comment]
等我有空了 补一下，你如果紧急的话可以自己先搞一下

**Comment by haitang1894** [comment]
已实现
