### ISSUE TITLE
为什么设置了keepAlive但是没起效果呢？

### ISSUE THREAD

**Issue by mxian** [haitang1894/pea#7]
routes.ts设置了keepAlive：
![image](https://github.com/user-attachments/assets/966a0862-dde5-41cc-ad55-3492d713b5d3)

页面：
![image](https://github.com/user-attachments/assets/5d2db8ee-55df-47d5-9777-b350dc4bbf7f)

我在页面上输入了一些文字后，切换tab，再回来，页面数据没有缓存，是不是我哪里设置的不对呢？

**Comment by haitang1894** [comment]
前端要去前端社区问呢





------------------ 原始邮件 ------------------
发件人: mxian ***@***.***&gt;
发送时间: 2024年8月27日 16:04
收件人: haitang1894/pea ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [haitang1894/pea] 为什么设置了keepAlive但是没起效果呢？ (Issue #7)





 
routes.ts设置了keepAlive：
 image.png (view on web)
 
`
 
 
 
 
 小
 
 
 中
 
 
 大
 
 
 
 
 
 
 
 
 
 
 
 
 
 <n-button attr-type="button" @click="handleValidateClick"&gt;
 验证
 
 
 


   <pre&gt;{{ JSON.stringify(formValue, null, 2) }}</pre&gt; </NCard&gt;     <script lang="ts"&gt; import {defineComponent, ref} from 'vue' import type {FormInst} from 'naive-ui' import {useMessage} from 'naive-ui' export default defineComponent({   setup() {     const formRef = ref(null)     const message = useMessage()     return {       formRef,       size: ref<'small' | 'medium' | 'large'&gt;('medium'),       formValue: ref({         user: {           name: '',           age: ''         },         phone: ''       }),       rules: {         user: {           name: {             required: true,             message: '请输入姓名',             trigger: 'blur'           },           age: {             required: true,             message: '请输入年龄',             trigger: ['input', 'blur']           }         },         phone: {           required: true,           message: '请输入电话号码',           trigger: ['input']         }       },       handleValidateClick(e: MouseEvent) {         e.preventDefault()         formRef.value?.validate((errors) =&gt; {           if (!errors) {             message.success('Valid')           } else {             console.log(errors)             message.error('Invalid')           }         })       }     }   } }) </script&gt; <style scoped&gt;</style&gt; 


`
 
我在页面上输入了一些文字后，切换tab，再回来，页面数据没有缓存，是不是我哪里设置的不对呢？

**Comment by mxian** [comment]
> 前端要去前端社区问呢
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: mxian ***@***.***&gt; 发送时间: 2024年8月27日 16:04 收件人: haitang1894/pea ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [haitang1894/pea] 为什么设置了keepAlive但是没起效果呢？ (Issue #7) routes.ts设置了keepAlive： image.png (view on web) ` 小 中 大 <n-button attr-type="button" @click="handleValidateClick"&gt; 验证 <pre&gt;{{ JSON.stringify(formValue, null, 2) }}</pre&gt; </NCard&gt; <script lang="ts"&gt; import {defineComponent, ref} from 'vue' import type {FormInst} from 'naive-ui' import {useMessage} from 'naive-ui' export default defineComponent({ setup() { const formRef = ref(null) const message = useMessage() return { formRef, size: ref<'small' | 'medium' | 'large'&gt;('medium'), formValue: ref({ user: { name: '', age: '' }, phone: '' }), rules: { user: { name: { required: true, message: '请输入姓名', trigger: 'blur' }, age: { required: true, message: '请输入年龄', trigger: ['input', 'blur'] } }, phone: { required: true, message: '请输入电话号码', trigger: ['input'] } }, handleValidateClick(e: MouseEvent) { e.preventDefault() formRef.value?.validate((errors) =&gt; { if (!errors) { message.success('Valid') } else { console.log(errors) message.error('Invalid') } }) } } } }) </script&gt; <style scoped&gt;</style&gt; ` 我在页面上输入了一些文字后，切换tab，再回来，页面数据没有缓存，是不是我哪里设置的不对呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

问错地方了，不好意思
