### ISSUE TITLE
sql文件内t_sys_user_role表好像有一个笔误

### ISSUE THREAD

**Issue by DreemurrY** [haitang1894/pea#8]
sql文件内t_sys_user_role表内出现`creator_id`和`creator_by`两个键,没有`create_id`和`create_by`
其它表内均有`create_id`和`create_by`
猜测为笔误写错了(XD
~也许我可以交一个pr蹭点贡献~

**Comment by haitang1894** [comment]
这个我改了，代码一直在堆压，太忙了 好久没更新了，这2天我更新一下新的
